# 01 — Data Understanding

## 1. Imports

In [1]:
import sys 
from pathlib import Path

ROOT = Path.cwd().parent

if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

In [2]:
import numpy as np
import pandas as pd
from src.data_loading import load_X_test, load_X_train, load_y_train, load_sample_submission

## 2. Chargement des données

In [3]:
X_train, y_train, X_test, sample_submission = load_X_train(), load_y_train(), load_X_test(), load_sample_submission()

## 3. Dimensions et colonnes

In [4]:
print(f"X_train shape = {X_train.shape}")
print(f"y_train shape = {y_train.shape}")
print(f"X_test shape = {X_test.shape}")
print(f"sample_submission shape = {sample_submission.shape}")

X_train shape = (527073, 45)
y_train shape = (527073, 2)
X_test shape = (31870, 45)
sample_submission shape = (31870, 2)

In [5]:
print(f"Les colonnes de X_train sont {list(X_train.columns)}\n\n\n")
print(f"Les colonnes de X_test sont {list(X_test.columns)}\n\n\n")
print(f"Les colonnes de y_train sont {list(y_train.columns)}")
print(f"Les colonnes de sample_submission sont {list(sample_submission.columns)}")

Les colonnes de X_train sont ['ROW_ID', 'TS', 'ALLOCATION', 'RET_20', 'RET_19', 'RET_18', 'RET_17', 'RET_16', 'RET_15', 'RET_14', 'RET_13', 'RET_12', 'RET_11', 'RET_10', 'RET_9', 'RET_8', 'RET_7', 'RET_6', 'RET_5', 'RET_4', 'RET_3', 'RET_2', 'RET_1', 'SIGNED_VOLUME_20', 'SIGNED_VOLUME_19', 'SIGNED_VOLUME_18', 'SIGNED_VOLUME_17', 'SIGNED_VOLUME_16', 'SIGNED_VOLUME_15', 'SIGNED_VOLUME_14', 'SIGNED_VOLUME_13', 'SIGNED_VOLUME_12', 'SIGNED_VOLUME_11', 'SIGNED_VOLUME_10', 'SIGNED_VOLUME_9', 'SIGNED_VOLUME_8', 'SIGNED_VOLUME_7', 'SIGNED_VOLUME_6', 'SIGNED_VOLUME_5', 'SIGNED_VOLUME_4', 'SIGNED_VOLUME_3', 'SIGNED_VOLUME_2', 'SIGNED_VOLUME_1', 'MEDIAN_DAILY_TURNOVER', 'GROUP']



Les colonnes de X_test sont ['ROW_ID', 'TS', 'ALLOCATION', 'RET_20', 'RET_19', 'RET_18', 'RET_17', 'RET_16', 'RET_15', 'RET_14', 'RET_13', 'RET_12', 'RET_11', 'RET_10', 'RET_9', 'RET_8', 'RET_7', 'RET_6', 'RET_5', 'RET_4', 'RET_3', 'RET_2', 'RET_1', 'SIGNED_VOLUME_20', 'SIGNED_VOLUME_19', 'SIGNED_VOLUME_18', 'SIGNED_VOLUME_17', 'SIGNED_VOLUME_16', 'SIGNED_VOLUME_15', 'SIGNED_VOLUME_14', 'SIGNED_VOLUME_13', 'SIGNED_VOLUME_12', 'SIGNED_VOLUME_11', 'SIGNED_VOLUME_10', 'SIGNED_VOLUME_9', 'SIGNED_VOLUME_8', 'SIGNED_VOLUME_7', 'SIGNED_VOLUME_6', 'SIGNED_VOLUME_5', 'SIGNED_VOLUME_4', 'SIGNED_VOLUME_3', 'SIGNED_VOLUME_2', 'SIGNED_VOLUME_1', 'MEDIAN_DAILY_TURNOVER', 'GROUP']



Les colonnes de y_train sont ['ROW_ID', 'target']
Les colonnes de sample_submission sont ['ROW_ID', 'prediction']

## 4. Aperçu rapide

In [6]:
X_train.head()

,ROW_ID,TS,ALLOCATION,RET_20,RET_19,RET_18,RET_17,RET_16,RET_15,RET_14,...,SIGNED_VOLUME_8,SIGNED_VOLUME_7,SIGNED_VOLUME_6,SIGNED_VOLUME_5,SIGNED_VOLUME_4,SIGNED_VOLUME_3,SIGNED_VOLUME_2,SIGNED_VOLUME_1,MEDIAN_DAILY_TURNOVER,GROUP
0,0,DATE_0001,ALLOCATION_01,-0.018192,-0.000306,-0.006881,-0.002393,0.000507,-0.001270,-0.002539,...,0.818730,0.941014,0.714129,-0.323847,0.525097,0.363601,-0.219328,NaN,0.096905,1
1,1,DATE_0001,ALLOCATION_02,-0.006394,-0.001059,0.001565,0.000033,0.002829,0.001725,0.000875,...,-1.390336,-0.651784,-0.896826,-0.636931,-1.074450,-0.748884,-0.718912,NaN,0.009974,4
2,2,DATE_0001,ALLOCATION_03,-0.016587,-0.004517,-0.005306,0.004314,0.006471,-0.005868,-0.005030,...,0.961318,0.452482,1.588321,0.790039,1.394445,0.493521,0.268094,NaN,0.044186,1
3,3,DATE_0001,ALLOCATION_04,-0.005344,0.002790,0.006937,-0.004246,-0.005051,-0.000330,-0.000117,...,-0.483377,-0.565114,-0.631710,-0.663300,-1.615905,-0.959046,-0.478789,NaN,0.001150,2
4,4,DATE_0001,ALLOCATION_05,-0.010506,-0.005491,0.007752,-0.012299,0.002191,0.003282,0.000495,...,0.268005,0.757707,1.524626,1.565541,1.563963,1.063209,0.921333,NaN,NaN,4

In [7]:
X_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 527073 entries, 0 to 527072
Data columns (total 45 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ROW_ID                 527073 non-null  int64
 1   TS                     527073 non-null  str
 2   ALLOCATION             527073 non-null  str
 3   RET_20                 527015 non-null  float64
 4   RET_19                 527023 non-null  float64
 5   RET_18                 527031 non-null  float64
 6   RET_17                 527039 non-null  float64
 7   RET_16                 527047 non-null  float64
 8   RET_15                 527055 non-null  float64
 9   RET_14                 527060 non-null  float64
 10  RET_13                 527064 non-null  float64
 11  RET_12                 527067 non-null  float64
 12  RET_11                 527069 non-null  float64
 13  RET_10                 527071 non-null  float64
 14  RET_9                  527073 non-null  float64
 15  RET_8                  527073 non-null  float64
 16  RET_7                  527073 non-null  float64
 17  RET_6                  527073 non-null  float64
 18  RET_5                  527073 non-null  float64
 19  RET_4                  527073 non-null  float64
 20  RET_3                  527073 non-null  float64
 21  RET_2                  527073 non-null  float64
 22  RET_1                  527073 non-null  float64
 23  SIGNED_VOLUME_20       518575 non-null  float64
 24  SIGNED_VOLUME_19       524071 non-null  float64
 25  SIGNED_VOLUME_18       526214 non-null  float64
 26  SIGNED_VOLUME_17       527015 non-null  float64
 27  SIGNED_VOLUME_16       527023 non-null  float64
 28  SIGNED_VOLUME_15       527031 non-null  float64
 29  SIGNED_VOLUME_14       527039 non-null  float64
 30  SIGNED_VOLUME_13       527047 non-null  float64
 31  SIGNED_VOLUME_12       527055 non-null  float64
 32  SIGNED_VOLUME_11       527060 non-null  float64
 33  SIGNED_VOLUME_10       527064 non-null  float64
 34  SIGNED_VOLUME_9        527067 non-null  float64
 35  SIGNED_VOLUME_8        527069 non-null  float64
 36  SIGNED_VOLUME_7        527071 non-null  float64
 37  SIGNED_VOLUME_6        527073 non-null  float64
 38  SIGNED_VOLUME_5        527073 non-null  float64
 39  SIGNED_VOLUME_4        527073 non-null  float64
 40  SIGNED_VOLUME_3        527073 non-null  float64
 41  SIGNED_VOLUME_2        527073 non-null  float64
 42  SIGNED_VOLUME_1        139567 non-null  float64
 43  MEDIAN_DAILY_TURNOVER  523435 non-null  float64
 44  GROUP                  527073 non-null  int64
dtypes: float64(41), int64(2), str(2)
memory usage: 181.0 MB

In [8]:
X_train.isnull().sum().sum()

np.int64(404027)

In [9]:
y_train.head()

   ROW_ID    target
0       0  0.009210
1       1  0.000405
2       2  0.005967
3       3 -0.000542
4       4 -0.002579

In [10]:
y_train.isnull().sum()

ROW_ID    0
target    0
dtype: int64

In [11]:
X_test.isnull().sum().sum()

np.int64(25801)

In [12]:
sample_submission.head()

   ROW_ID  prediction
0  527073           0
1  527074           0
2  527075           0
3  527076           1
4  527077           0

In [13]:
X_test.head()

,ROW_ID,TS,ALLOCATION,RET_20,RET_19,RET_18,RET_17,RET_16,RET_15,RET_14,...,SIGNED_VOLUME_8,SIGNED_VOLUME_7,SIGNED_VOLUME_6,SIGNED_VOLUME_5,SIGNED_VOLUME_4,SIGNED_VOLUME_3,SIGNED_VOLUME_2,SIGNED_VOLUME_1,MEDIAN_DAILY_TURNOVER,GROUP
0,527073,DATE_2523,ALLOCATION_01,-0.000523,0.000066,-0.001601,0.002030,-0.000137,-0.001506,0.000479,...,-1.124653,-1.263611,-1.177919,-1.251840,-1.242161,-1.428584,-1.187617,NaN,0.067261,1
1,527074,DATE_2523,ALLOCATION_02,0.002868,-0.000870,0.000609,0.003156,0.001140,0.000728,0.002079,...,-1.310546,-0.925154,0.202205,0.132192,-1.331976,-1.240283,-0.398260,NaN,0.014322,4
2,527075,DATE_2523,ALLOCATION_03,-0.000435,0.003141,0.001410,-0.011531,-0.000685,0.002088,-0.003898,...,1.402281,1.483750,1.152671,1.023963,0.817952,0.944071,1.020218,NaN,0.044605,1
3,527076,DATE_2523,ALLOCATION_04,0.000881,-0.000608,-0.001570,0.002289,-0.001712,0.003227,-0.001871,...,1.337044,2.114258,1.508769,2.179684,2.461713,0.692128,-2.120144,NaN,0.000807,2
4,527077,DATE_2523,ALLOCATION_05,-0.001371,-0.000062,0.002873,-0.002477,0.000894,0.000972,0.002024,...,0.905229,1.050951,0.863661,1.146283,1.738564,1.462726,1.505504,NaN,0.000550,4

## 5. Alignement des identifiants

Vérifions l'alignement des index de X_train et y_train

In [14]:
print(f"Est que X_train et y_train ont le même nombre de lignes : {len(X_train) == len(y_train)}")
print(f"Est ce que les ROW_ID de X_train sont alignés avec les ROW_ID de y_train : {X_train["ROW_ID"].equals(y_train["ROW_ID"])}")

Est que X_train et y_train ont le même nombre de lignes : True
Est ce que les ROW_ID de X_train sont alignés avec les ROW_ID de y_train : True

Colonnes avec des valeurs manquantes dans X_train comme les ROW_ID sont alignés dans le même ordre, on pourra ajouter la target à X_train sans merge complexe.

In [15]:
print(f"Est que X_train et y_train ont le même nombre de lignes : {len(X_test) == len(sample_submission)}")
print(f"Est ce que les ROW_ID de X_train sont alignés avec les ROW_ID de y_train : {X_test["ROW_ID"].equals(sample_submission["ROW_ID"])}")

Est que X_train et y_train ont le même nombre de lignes : True
Est ce que les ROW_ID de X_train sont alignés avec les ROW_ID de y_train : True

In [16]:
print(f"Est ce que les colonnes de X_train sont les mêmes que celles de X_test : {set(X_train.columns) == set(X_test.columns)}")

Est ce que les colonnes de X_train sont les mêmes que celles de X_test : True

In [17]:
print(f"Le nombre de ROW_ID dupliqués dans X_train est égal à {X_train.duplicated("ROW_ID").sum()}")
print(f"Le nombre de ROW_ID dupliqués dans y_train est égal à {y_train.duplicated("ROW_ID").sum()}")
print(f"Le nombre de ROW_ID dupliqués dans X_test est égal à {X_test.duplicated("ROW_ID").sum()}")
print(f"Le nombre de ROW_ID dupliqués dans sample_submission est égal à {sample_submission.duplicated("ROW_ID").sum()}")

Le nombre de ROW_ID dupliqués dans X_train est égal à 0
Le nombre de ROW_ID dupliqués dans y_train est égal à 0
Le nombre de ROW_ID dupliqués dans X_test est égal à 0
Le nombre de ROW_ID dupliqués dans sample_submission est égal à 0

## 6. Valeurs manquantes

In [18]:
df_features_null_X_train = X_train.isnull().sum().reset_index()

In [19]:
df_features_null_X_train.columns = ["feature", "nb_null"]

In [20]:
df_features_null_X_train = df_features_null_X_train[df_features_null_X_train["nb_null"] >= 1]

In [21]:
df_features_null_X_train

                  feature  nb_null
3                  RET_20       58
4                  RET_19       50
5                  RET_18       42
6                  RET_17       34
7                  RET_16       26
8                  RET_15       18
9                  RET_14       13
10                 RET_13        9
11                 RET_12        6
12                 RET_11        4
13                 RET_10        2
23       SIGNED_VOLUME_20     8498
24       SIGNED_VOLUME_19     3002
25       SIGNED_VOLUME_18      859
26       SIGNED_VOLUME_17       58
27       SIGNED_VOLUME_16       50
28       SIGNED_VOLUME_15       42
29       SIGNED_VOLUME_14       34
30       SIGNED_VOLUME_13       26
31       SIGNED_VOLUME_12       18
32       SIGNED_VOLUME_11       13
33       SIGNED_VOLUME_10        9
34        SIGNED_VOLUME_9        6
35        SIGNED_VOLUME_8        4
36        SIGNED_VOLUME_7        2
42        SIGNED_VOLUME_1   387506
43  MEDIAN_DAILY_TURNOVER     3638

In [22]:
df_features_null_X_test = X_test.isnull().sum().reset_index()

In [23]:
df_features_null_X_test.columns = ["features","nb_null"]

In [24]:
df_features_null_X_test = df_features_null_X_test[df_features_null_X_test["nb_null"] >= 1]

In [25]:
df_features_null_X_test

                 features  nb_null
3                  RET_20        4
4                  RET_19        4
5                  RET_18        4
6                  RET_17        4
7                  RET_16        4
8                  RET_15        4
9                  RET_14        4
10                 RET_13        4
11                 RET_12        4
12                 RET_11      256
13                 RET_10        2
23       SIGNED_VOLUME_20      955
24       SIGNED_VOLUME_19      191
25       SIGNED_VOLUME_18        4
26       SIGNED_VOLUME_17        4
27       SIGNED_VOLUME_16        4
28       SIGNED_VOLUME_15        4
29       SIGNED_VOLUME_14        4
30       SIGNED_VOLUME_13        4
31       SIGNED_VOLUME_12      258
32       SIGNED_VOLUME_11        4
33       SIGNED_VOLUME_10        4
34        SIGNED_VOLUME_9        4
35        SIGNED_VOLUME_8        2
36        SIGNED_VOLUME_7        2
42        SIGNED_VOLUME_1    23914
43  MEDIAN_DAILY_TURNOVER      149

## Conclusion du data understanding

- Les fichiers sont correctement chargés.
- X_train et y_train ont le même nombre de lignes.
- Les ROW_ID de X_train et y_train sont alignés.
- X_test et sample_submission ont le même nombre de lignes.
- Les ROW_ID de X_test et sample_submission sont alignés.
- X_train et X_test ont les mêmes colonnes.
- Les valeurs manquantes sont surtout présentes dans certaines colonnes SIGNED_VOLUME.
- La target est continue et devra être transformée en variable binaire plus tard.